In [2]:
import pandas as pd
import numpy as np
import os

pd.options.display.max_columns = None

In [3]:
os.chdir('/Users/juanantoniomschz/Documents/Proyectos/itesm_segregacion/')

In [4]:
path_censo = '~/Documents/Proyectos/itesm_segregacion/data/Censo/RESAGEBURB_19CSV20.csv'
# path_censo = '~/Documents/Proyectos/itesm_segregacion/data/Censo/agebs_2021.csv'

df_censo = pd.read_csv(path_censo, encoding='utf-8', na_values = ['*'])
df_censo = df_censo[df_censo['NOM_LOC']=='Total AGEB urbana'].reset_index().drop('index', axis = 1)

# df_censo = pd.read_csv(path_censo, encoding='utf-8', na_values = ['*'])
df_censo.head()

/Users/juanantoniomschz/opt/anaconda3/lib/python3.8/site-packages/IPython/core/interactiveshell.py:3146: DtypeWarning: Columns (11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,42,43,44,45,46,47,48,49,50,51,52,53,54,55,56,57,58,59,60,61,62,63,64,65,66,67,68,69,70,71,72,73,74,75,76,77,78,79,80,81,82,83,84,85,86,87,88,89,90,91,92,93,94,95,96,97,98,99,100,101,102,103,104,105,106,107,108,109,110,111,112,113,114,115,116,117,118,119,120,121,122,123,124,125,126,127,128,129,130,131,132,133,134,135,136,137,138,139,140,141,142,143,144,145,146,147,148,149,150,151,152,153,154,155,156,157,158,159,160,161,162,163,164,165,166,167,168,169,170,171,172,173,174,175,176,179,180,181,182,183,184,185,186,187,188,189,190,191,192,193,194,195,196,197,198,199,200,201,202,203,204,205,206,207,208,209,210,211,212,213,214,215,216,217,218,219,220,221,222,223,224,225,226,227,228,229) have mixed types.Specify dtype option on import or set low_memory=False.
  has_raised = await self.run_ast_nodes(code_ast.body, cell_name,

,ENTIDAD,NOM_ENT,MUN,NOM_MUN,LOC,NOM_LOC,AGEB,MZA,POBTOT,POBFEM,POBMAS,P_0A2,P_0A2_F,P_0A2_M,P_3YMAS,P_3YMAS_F,P_3YMAS_M,P_5YMAS,P_5YMAS_F,P_5YMAS_M,P_12YMAS,P_12YMAS_F,P_12YMAS_M,P_15YMAS,P_15YMAS_F,P_15YMAS_M,P_18YMAS,P_18YMAS_F,P_18YMAS_M,P_3A5,P_3A5_F,P_3A5_M,P_6A11,P_6A11_F,P_6A11_M,P_8A14,P_8A14_F,P_8A14_M,P_12A14,P_12A14_F,P_12A14_M,P_15A17,P_15A17_F,P_15A17_M,P_18A24,P_18A24_F,P_18A24_M,P_15A49_F,P_60YMAS,P_60YMAS_F,P_60YMAS_M,REL_H_M,POB0_14,POB15_64,POB65_MAS,PROM_HNV,PNACENT,PNACENT_F,PNACENT_M,PNACOE,PNACOE_F,PNACOE_M,PRES2015,PRES2015_F,PRES2015_M,PRESOE15,PRESOE15_F,PRESOE15_M,P3YM_HLI,P3YM_HLI_F,P3YM_HLI_M,P3HLINHE,P3HLINHE_F,P3HLINHE_M,P3HLI_HE,P3HLI_HE_F,P3HLI_HE_M,P5_HLI,P5_HLI_NHE,P5_HLI_HE,PHOG_IND,POB_AFRO,POB_AFRO_F,POB_AFRO_M,PCON_DISC,PCDISC_MOT,PCDISC_VIS,PCDISC_LENG,PCDISC_AUD,PCDISC_MOT2,PCDISC_MEN,PCON_LIMI,PCLIM_CSB,PCLIM_VIS,PCLIM_HACO,PCLIM_OAUD,PCLIM_MOT2,PCLIM_RE_CO,PCLIM_PMEN,PSIND_LIM,P3A5_NOA,P3A5_NOA_F,P3A5_NOA_M,P6A11_NOA,P6A11_NOAF,P6A11_NOAM,P12A14NOA,P12A14NOAF,P12A14NOAM,P15A17A,P15A17A_F,P15A17A_M,P18A24A,P18A24A_F,P18A24A_M,P8A14AN,P8A14AN_F,P8A14AN_M,P15YM_AN,P15YM_AN_F,P15YM_AN_M,P15YM_SE,P15YM_SE_F,P15YM_SE_M,P15PRI_IN,P15PRI_INF,P15PRI_INM,P15PRI_CO,P15PRI_COF,P15PRI_COM,P15SEC_IN,P15SEC_INF,P15SEC_INM,P15SEC_CO,P15SEC_COF,P15SEC_COM,P18YM_PB,P18YM_PB_F,P18YM_PB_M,GRAPROES,GRAPROES_F,GRAPROES_M,PEA,PEA_F,PEA_M,PE_INAC,PE_INAC_F,PE_INAC_M,POCUPADA,POCUPADA_F,POCUPADA_M,PDESOCUP,PDESOCUP_F,PDESOCUP_M,PSINDER,PDER_SS,PDER_IMSS,PDER_ISTE,PDER_ISTEE,PAFIL_PDOM,PDER_SEGP,PDER_IMSSB,PAFIL_IPRIV,PAFIL_OTRAI,P12YM_SOLT,P12YM_CASA,P12YM_SEPA,PCATOLICA,PRO_CRIEVA,POTRAS_REL,PSIN_RELIG,TOTHOG,HOGJEF_F,HOGJEF_M,POBHOG,PHOGJEF_F,PHOGJEF_M,VIVTOT,TVIVHAB,TVIVPAR,VIVPAR_HAB,VIVPARH_CV,TVIVPARHAB,VIVPAR_DES,VIVPAR_UT,OCUPVIVPAR,PROM_OCUP,PRO_OCUP_C,VPH_PISODT,VPH_PISOTI,VPH_1DOR,VPH_2YMASD,VPH_1CUART,VPH_2CUART,VPH_3YMASC,VPH_C_ELEC,VPH_S_ELEC,VPH_AGUADV,VPH_AEASP,VPH_AGUAFV,VPH_TINACO,VPH_CISTER,VPH_EXCSA,VPH_LETR,VPH_DRENAJ,VPH_NODREN,VPH_C_SERV,VPH_NDEAED,VPH_DSADMA,VPH_NDACMM,VPH_SNBIEN,VPH_REFRI,VPH_LAVAD,VPH_HMICRO,VPH_AUTOM,VPH_MOTO,VPH_BICI,VPH_RADIO,VPH_TV,VPH_PC,VPH_TELEF,VPH_CEL,VPH_INTER,VPH_STVP,VPH_SPMVPI,VPH_CVJ,VPH_SINRTV,VPH_SINLTC,VPH_SINCINT,VPH_SINTIC
0,19,Nuevo León,1,Abasolo,1,Total AGEB urbana,0021,0,1114,583.0,531.0,58,32,26,1054,550,504,1013,527,486,883,460,423,833,433,400,776,407,369,60,32,28,111,58,53,126,66,60,50,27,23,57,26,31,124,72,52,286,145,76,69,91.08,279,733,100,2.18,980,508,472,114,61,53,996,518,478,9,3,6,NaN,NaN,0,0,0,0,NaN,NaN,0,NaN,0,NaN,6,NaN,NaN,0,25,15,7,7,7,9,4,87,36,51,4,28,7,12,7,988,24,13,11,14,9,5,7,5,NaN,36,17,19,37,22,15,NaN,0,NaN,13,8,5,11,7,4,46,27,19,88,44,44,15,5,10,285,139,146,341,182,159,9.9,9.95,9.85,378,104,274,500,353,147,370,104,266,8,0,8,8,1094,701,54,12,0,258,0,87,NaN,269,487,122,859,169,0,76,308,97,211,1114,332,782,442,308.0,435,301,308,308,94,40,1114,3.62,0.88,307,0,97,211,6,43,258,307,0,307,307,0,14,0,304,NaN,307,0,307,0,304,114,NaN,298,276,197,190,13,29,236,299,105,50,284,160,141,62,54,4,17,133,NaN
1,19,Nuevo León,1,Abasolo,1,Total AGEB urbana,0036,0,803,407.0,396.0,47,21,26,756,386,370,733,372,361,638,322,316,594,303,291,551,277,274,38,22,16,80,42,38,99,45,54,44,19,25,43,26,17,97,49,48,203,101,60,41,97.3,209,535,59,2.24,667,331,336,128,72,56,712,358,354,16,11,5,0,0,0,0,0,0,0,0,0,0,0,0,0,NaN,0,NaN,61,18,37,4,10,9,9,102,26,79,3,16,NaN,13,7,639,10,7,3,3,NaN,NaN,3,NaN,NaN,32,21,11,25,12,13,NaN,0,NaN,17,10,7,22,11,11,31,18,13,66,39,27,9,5,4,217,107,110,224,107,117,9.59,9.5,9.7,316,84,232,320,238,82,300,82,218,16,NaN,14,4,799,483,6,6,0,224,0,92,NaN,209,350,79,612,153,0,38,214,60,154,803,207,596,325,214.0,325,214,214,214,67,44,803,3.75,0.93,214,0,80,134,10,21,183,213,NaN,213,213,NaN,10,0,212,NaN,213,NaN,212,0,212,76,NaN,208,183,141,136,15,36,154,206,66,47,198,93,110,36,29,5,14,109,3
2,19,Nuevo León,1,Abasolo,1,Total AGEB urbana,0040,0,65,36.0,29.0,3,NaN,NaN,62,35,27,59,32,27,51,27,24,50,27,23,47,25,22,4,4,0,7,4,3,6,3,3,NaN,0,NaN,3,NaN,NaN,4,NaN,NaN,15,12,6,6,80.56,15,41,9,2.48,52,28,24,11,6,5,58,31,27,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,7,5,3,NaN,NaN,NaN,0,5,NaN,NaN,NaN,0,NaN,NaN,NaN,51,NaN,NaN,0,0,0,0,0,0,0,NaN,NaN,0,0,0,0,0,0,0,3,NaN,NaN,3,NaN,NaN,3,3,0,5,3,NaN,NaN,0,NaN,24,12,12,13,7,6,8.44,8.22,8.7,24,10,14,26,17,9,22,10,12,NaN,0,NaN,NaN,61,39,0,0,0,18,0,4,0,15,23,13,52,11,0,0,20,6,14,65,17,48,24,20.0,24,20,20,20,4,0,65,3.25,0.87,20,0,9,11,0,3,17,20,0,20,20,0,0,0,18,NaN,20,0,20,0,18,8,0,20,18,9,11,NaN,3,14,19,4,NaN,18,5,7,NaN,0,0,NaN,13,0
3,19,Nuevo León,1,Abasolo,1,Total AGEB urbana,0055,0,10,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,19,Nuevo León,2,Agualeguas,1,Total AGEB urbana,0207,0,268,136.0,132.0,9,4,5,259,132,127,253,128,125,229,112,117,214,106,108,208,104,104,9,7,NaN,21,13,8,27,15,12,15,6,9,6,NaN,4,24,10,14,57,59,29,30,97.06,54,168,46,2.73,206,101,105,46,27,19,246,124,122,4,NaN,NaN,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,18,8,11,NaN,4,5,NaN,41,14,28,0,12,0,3,0,209,3,NaN,NaN,0,0,0,0,0,0,3,NaN,NaN,5,NaN,4,0,0,0,17,9,8,17,10,7,34,14,20,24,13,11,8,4,4,60,27,33,68,36,32,8.19,8.28,8.09,116,35,81,113,77,36,116,35,81,0,0,0,11,257,64,15,NaN,0,166,0,NaN,9,54,139,36,220,31,0,17,97,21,76,268,51,217,177,97.0,172,92,97,97,47,33,268,2.76,0.65,97,0,23,74,NaN,3,92,97,0,97,96,0,7,0,95,NaN,95,NaN,95,0,95,21,0,96,86,75,75,7,27,55,93,24,28,83,39,60,8,5,3,12,55,NaN

In [17]:
cols = ['NOM_ENT', 'NOM_MUN', 'AGEB', 'VIVPARH_CV', 'OCUPVIVPAR', 'VPH_1DOR', 'VPH_2YMASD',
        'VPH_LAVAD', 'VPH_REFRI', 'VPH_STVP', 'VPH_TELEF', 'VPH_INTER', 'VPH_PC', 'VPH_CVJ','VPH_AUTOM']

df_censo_var = df_censo[cols] # seleccionamos las columnas objetivo
df_censo_var.head(5)

,NOM_ENT,NOM_MUN,AGEB,VIVPARH_CV,OCUPVIVPAR,VPH_1DOR,VPH_2YMASD,VPH_LAVAD,VPH_REFRI,VPH_STVP,VPH_TELEF,VPH_INTER,VPH_PC,VPH_CVJ,VPH_AUTOM
0,Nuevo León,Abasolo,0021,308,1114,97,211,276,298,141,50,160,105,54,190
1,Nuevo León,Abasolo,0036,214,803,80,134,183,208,110,47,93,66,29,136
2,Nuevo León,Abasolo,0040,20,65,9,11,18,20,7,NaN,5,4,0,11
3,Nuevo León,Abasolo,0055,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Nuevo León,Agualeguas,0207,97,268,23,74,86,96,60,28,39,24,5,75

In [18]:
df_censo_var.columns = ['Entidad', 'Municipio', 'AGEB', 'VIVPARH_CV', 'Ocupantes', '1dorm', '2masdorm',
                        'Lavadora', 'Refri', 'TVPaga', 'Telefono', 'Internet', 'PC', 'Consola', 'Auto'] 

for i in df_censo_var.columns[3:]:
    
    df_censo_var[i] = pd.to_numeric(df_censo_var[i]) # cambiamos el formato de las columnas a numeros
    
df_censo_var.describe()

<ipython-input-18-3df3c679942f>:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_censo_var[i] = pd.to_numeric(df_censo_var[i]) # cambiamos el formato de las columnas a numeros

,VIVPARH_CV,Ocupantes,1dorm,2masdorm,Lavadora,Refri,TVPaga,Telefono,Internet,PC,Consola,Auto
count,2687.000000,2718.000000,2648.000000,2687.000000,2701.000000,2711.000000,2672.000000,2631.000000,2657.000000,2647.000000,2596.000000,2694.000000
mean,591.435802,2042.510302,140.591767,450.731299,514.606442,566.964220,290.655314,347.230711,427.643583,294.948621,116.485362,345.052710
std,489.140817,1753.133358,125.769991,390.309347,429.100025,474.709685,251.126854,324.207629,381.335280,292.495636,130.262404,313.400936
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,161.000000,509.500000,42.750000,112.500000,138.000000,149.000000,82.750000,69.000000,94.000000,64.000000,22.000000,96.000000
50%,521.000000,1704.500000,116.000000,376.000000,446.000000,495.000000,240.000000,269.000000,351.000000,215.000000,78.000000,278.000000
75%,913.000000,3238.000000,204.000000,702.000000,805.000000,886.000000,442.000000,552.000000,668.000000,434.500000,164.000000,512.000000
max,3250.000000,11293.000000,957.000000,2531.000000,3076.000000,3230.000000,1731.000000,1921.000000,2765.000000,2162.000000,927.000000,2516.000000

In [19]:
df_cons = df_censo_var[df_censo_var['1dorm']>0] # que existan viviendas con más de 1 dormitorio en la AGEB
df_cons = df_cons[df_cons.isnull().sum(1)==0] # que la AGEB no presente valores nulos

viv_drop = (df_censo_var[df_censo_var.isnull().sum(1)>0]['VIVPARH_CV'].sum()) # cuantas viviendas dropeamos
viv_rest = df_cons['VIVPARH_CV'].sum() # cuantas viviendas quedan

print('Se eliminaron {} viviendas, quedan restantes {} viviendas.\n'.format(int(viv_drop), int(viv_rest)))

elim = len(df_censo_var) - len(df_cons)  # cuantas agebs quitamos
ageb_rest = len(df_cons) # cuantas agebs quedan

print('Se eliminaron {} agebs. Quedan restantes {} agebs'.format(elim, ageb_rest))

df_cons.describe()

Se eliminaron 7934 viviendas, quedan restantes 1580907 viviendas.

Se eliminaron 409 agebs. Quedan restantes 2356 agebs

,VIVPARH_CV,Ocupantes,1dorm,2masdorm,Lavadora,Refri,TVPaga,Telefono,Internet,PC,Consola,Auto
count,2356.000000,2356.000000,2356.000000,2356.000000,2356.000000,2356.000000,2356.000000,2356.000000,2356.000000,2356.000000,2356.000000,2356.000000
mean,671.013158,2344.192275,156.917233,511.809847,587.129032,649.184635,328.030985,387.098896,481.121817,330.447368,128.096774,392.412564
std,470.311615,1690.868946,123.755719,378.596510,411.990795,455.451604,244.253967,319.611679,372.424923,290.910548,131.263324,307.158185
min,5.000000,10.000000,3.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,269.000000,912.000000,64.000000,189.000000,235.000000,259.000000,134.000000,119.750000,165.750000,107.000000,34.000000,155.000000
50%,622.500000,2113.500000,136.000000,463.000000,542.500000,602.000000,282.000000,328.000000,420.000000,254.500000,90.000000,327.000000
75%,962.000000,3443.250000,216.000000,739.000000,847.000000,930.250000,469.000000,580.000000,711.750000,468.000000,178.000000,545.250000
max,3250.000000,11293.000000,957.000000,2531.000000,3076.000000,3230.000000,1731.000000,1921.000000,2765.000000,2162.000000,927.000000,2516.000000

In [20]:
loop_var = ['Lavadora', 'Refri', 'TVPaga', 'Telefono', 'Internet', 'PC', 'Consola', 'Auto']

for i in loop_var:
    
    var = 'No' + i
    df_cons[var] = (df_cons['VIVPARH_CV'] - df_cons[i]).astype(float) # creamos variables negativas
    
df_cons.describe()

,VIVPARH_CV,Ocupantes,1dorm,2masdorm,Lavadora,Refri,TVPaga,Telefono,Internet,PC,Consola,Auto,NoLavadora,NoRefri,NoTVPaga,NoTelefono,NoInternet,NoPC,NoConsola,NoAuto
count,2356.000000,2356.000000,2356.000000,2356.000000,2356.000000,2356.000000,2356.000000,2356.000000,2356.000000,2356.000000,2356.000000,2356.000000,2356.000000,2356.000000,2356.000000,2356.000000,2356.000000,2356.000000,2356.000000,2356.000000
mean,671.013158,2344.192275,156.917233,511.809847,587.129032,649.184635,328.030985,387.098896,481.121817,330.447368,128.096774,392.412564,83.884126,21.828523,342.982173,283.914261,189.891341,340.565789,542.916384,278.600594
std,470.311615,1690.868946,123.755719,378.596510,411.990795,455.451604,244.253967,319.611679,372.424923,290.910548,131.263324,307.158185,99.482110,40.272620,269.210152,258.797461,183.791024,302.422225,389.547814,276.837260
min,5.000000,10.000000,3.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,5.000000,0.000000
25%,269.000000,912.000000,64.000000,189.000000,235.000000,259.000000,134.000000,119.750000,165.750000,107.000000,34.000000,155.000000,21.000000,3.000000,114.000000,99.000000,57.750000,106.000000,216.750000,65.000000
50%,622.500000,2113.500000,136.000000,463.000000,542.500000,602.000000,282.000000,328.000000,420.000000,254.500000,90.000000,327.000000,54.000000,10.000000,291.000000,216.000000,141.000000,258.000000,491.500000,192.000000
75%,962.000000,3443.250000,216.000000,739.000000,847.000000,930.250000,469.000000,580.000000,711.750000,468.000000,178.000000,545.250000,108.000000,25.000000,521.000000,378.250000,268.000000,497.000000,790.000000,425.000000
max,3250.000000,11293.000000,957.000000,2531.000000,3076.000000,3230.000000,1731.000000,1921.000000,2765.000000,2162.000000,927.000000,2516.000000,939.000000,887.000000,1775.000000,2517.000000,1863.000000,2212.000000,2442.000000,2118.000000

In [21]:
# Cuantas AGEBS fueron registradas incorrectamente en los dormitorios
dorms_mal = len(df_cons[(df_cons.loc[:, 'VIVPARH_CV'] - df_cons.loc[:, '1dorm'] - df_cons.loc[:, '2masdorm']) != 0])
print('{} AGEBS tienen mal registrada la cantidad de dormitorios.'.format(dorms_mal))

463 AGEBS tienen mal registrada la cantidad de dormitorios.

In [22]:
# Función para resolver el registro de dormitorios

def diff_num(x):
    
    '''
    x: es un dataframe con las columnas deseadas
    '''
    
    x = list(x)
    total = x.pop(0)
    
    suma = sum(x)

    for i in range(len(x)):
        x[i] = float(round((x[i]/suma) * total))
        
    return pd.Series(x)

In [23]:
df_cons[['1dorm', '2masdorm']] = df_cons[['VIVPARH_CV', '1dorm', '2masdorm']].apply(diff_num, axis = 1)
df_cons[['VIVPARH_CV','1dorm', '2masdorm']].describe()

        VIVPARH_CV        1dorm     2masdorm
count  2356.000000  2356.000000  2356.000000
mean    671.013158   157.404075   513.609083
std     470.311615   123.879771   378.898676
min       5.000000     3.000000     0.000000
25%     269.000000    64.000000   189.750000
50%     622.500000   137.000000   466.000000
75%     962.000000   216.000000   742.250000
max    3250.000000   957.000000  2532.000000

In [24]:
# Cuantas AGEBS fueron registradas incorrectamente en los dormitorios
dorms_mal = len(df_cons[(df_cons.loc[:, 'VIVPARH_CV'] - df_cons.loc[:, '1dorm'] - df_cons.loc[:, '2masdorm']) != 0])
print('{} AGEBS tienen mal registrada la cantidad de dormitorios.'.format(dorms_mal))

0 AGEBS tienen mal registrada la cantidad de dormitorios.

In [25]:
df_cons.describe()

,VIVPARH_CV,Ocupantes,1dorm,2masdorm,Lavadora,Refri,TVPaga,Telefono,Internet,PC,Consola,Auto,NoLavadora,NoRefri,NoTVPaga,NoTelefono,NoInternet,NoPC,NoConsola,NoAuto
count,2356.000000,2356.000000,2356.000000,2356.000000,2356.000000,2356.000000,2356.000000,2356.000000,2356.000000,2356.000000,2356.000000,2356.000000,2356.000000,2356.000000,2356.000000,2356.000000,2356.000000,2356.000000,2356.000000,2356.000000
mean,671.013158,2344.192275,157.404075,513.609083,587.129032,649.184635,328.030985,387.098896,481.121817,330.447368,128.096774,392.412564,83.884126,21.828523,342.982173,283.914261,189.891341,340.565789,542.916384,278.600594
std,470.311615,1690.868946,123.879771,378.898676,411.990795,455.451604,244.253967,319.611679,372.424923,290.910548,131.263324,307.158185,99.482110,40.272620,269.210152,258.797461,183.791024,302.422225,389.547814,276.837260
min,5.000000,10.000000,3.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,5.000000,0.000000
25%,269.000000,912.000000,64.000000,189.750000,235.000000,259.000000,134.000000,119.750000,165.750000,107.000000,34.000000,155.000000,21.000000,3.000000,114.000000,99.000000,57.750000,106.000000,216.750000,65.000000
50%,622.500000,2113.500000,137.000000,466.000000,542.500000,602.000000,282.000000,328.000000,420.000000,254.500000,90.000000,327.000000,54.000000,10.000000,291.000000,216.000000,141.000000,258.000000,491.500000,192.000000
75%,962.000000,3443.250000,216.000000,742.250000,847.000000,930.250000,469.000000,580.000000,711.750000,468.000000,178.000000,545.250000,108.000000,25.000000,521.000000,378.250000,268.000000,497.000000,790.000000,425.000000
max,3250.000000,11293.000000,957.000000,2532.000000,3076.000000,3230.000000,1731.000000,1921.000000,2765.000000,2162.000000,927.000000,2516.000000,939.000000,887.000000,1775.000000,2517.000000,1863.000000,2212.000000,2442.000000,2118.000000

In [38]:
df_cons = df_cons[['Entidad', 'Municipio', 'AGEB', 'VIVPARH_CV', 'Ocupantes', '1dorm',
       '2masdorm','TVPaga','NoTVPaga','Internet','NoInternet', 'PC','NoPC', 'Lavadora', 'NoLavadora',
        'Refri','NoRefri','Telefono','NoTelefono','Auto','NoAuto','Consola','NoConsola']]
df_cons.reset_index(inplace = True)
df_cons.drop(['index','Entidad'], axis = 1, inplace = True)
df_cons.head()

,Municipio,AGEB,VIVPARH_CV,Ocupantes,1dorm,2masdorm,TVPaga,NoTVPaga,Internet,NoInternet,PC,NoPC,Lavadora,NoLavadora,Refri,NoRefri,Telefono,NoTelefono,Auto,NoAuto,Consola,NoConsola
0,Abasolo,0021,308.0,1114.0,97.0,211.0,141.0,167.0,160.0,148.0,105.0,203.0,276.0,32.0,298.0,10.0,50.0,258.0,190.0,118.0,54.0,254.0
1,Abasolo,0036,214.0,803.0,80.0,134.0,110.0,104.0,93.0,121.0,66.0,148.0,183.0,31.0,208.0,6.0,47.0,167.0,136.0,78.0,29.0,185.0
2,Agualeguas,0207,97.0,268.0,23.0,74.0,60.0,37.0,39.0,58.0,24.0,73.0,86.0,11.0,96.0,1.0,28.0,69.0,75.0,22.0,5.0,92.0
3,Agualeguas,0230,107.0,229.0,34.0,73.0,63.0,44.0,72.0,35.0,40.0,67.0,98.0,9.0,105.0,2.0,75.0,32.0,69.0,38.0,4.0,103.0
4,Agualeguas,0245,59.0,154.0,20.0,39.0,36.0,23.0,31.0,28.0,20.0,39.0,50.0,9.0,58.0,1.0,33.0,26.0,42.0,17.0,4.0,55.0

In [39]:
df_cons.to_csv('data/Clean data/cons.csv')

In [37]:
df_cons['Municipio'].value_counts()

Monterrey                   461
Apodaca                     240
Guadalupe                   219
Juárez                      186
García                      156
General Escobedo            142
San Nicolás de los Garza    122
Santa Catarina              100
Cadereyta Jiménez            63
San Pedro Garza García       52
Linares                      52
Pesquería                    47
Montemorelos                 47
Sabinas Hidalgo              46
Santiago                     44
Ciénega de Flores            43
General Zuazua               39
Salinas Victoria             31
Allende                      29
El Carmen                    28
China                        20
Hidalgo                      19
Anáhuac                      17
Hualahuises                  13
General Bravo                11
Cerralvo                     10
Doctor Arroyo                10
Aramberri                    10
Galeana                      10
General Terán                 9
Lampazos de Naranjo           8
Villaldama                    6
Bustamante                    6
Mina                          6
Agualeguas                    6
Marín                         5
Doctor González               5
Higueras                      5
Melchor Ocampo                4
Los Ramones                   4
Iturbide                      4
Los Aldamas                   3
General Treviño               3
Mier y Noriega                3
General Zaragoza              3
Parás                         2
Abasolo                       2
Los Herreras                  2
Vallecillo                    1
Doctor Coss                   1
Rayones                       1
Name: Municipio, dtype: int64